language: node_js
env:
  global:
    - COV=true

    # CODECLIMATE_REPO_TOKEN
    - secure: "vWu/FG20Uc1JgcUmzH467bZ82BKLuRU0wfKnA6f4CGfOIHsiAL62MDA3KRqfsRpsss9JTyERQ2zm7iLEVXu4dOcKody9AsrZRWtC+wvuKBoAllUt6jZnNOgs7Hjac50TI68E0p4Hrz+0xqV+YlppU5I34mGlZ2EhmSTnZ0zdIgw="
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run build
  - npm run travis
after_success:
  - 'cat coverage/lcov.info | ./node_modules/.bin/codeclimate'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/31893c5fbae5d66e0a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false
