language: node_js
node_js:
  - "0.10"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - npm run build
  - npm run travis
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/31893c5fbae5d66e0a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false
