language: node_js
sudo: false
env:
  global:
    # CODECLIMATE_REPO_TOKEN
    - secure: "vWu/FG20Uc1JgcUmzH467bZ82BKLuRU0wfKnA6f4CGfOIHsiAL62MDA3KRqfsRpsss9JTyERQ2zm7iLEVXu4dOcKody9AsrZRWtC+wvuKBoAllUt6jZnNOgs7Hjac50TI68E0p4Hrz+0xqV+YlppU5I34mGlZ2EhmSTnZ0zdIgw="
    - BROWSER=Chrome_travis_ci
    - CHROME_BIN=chromium-browser
    - NODE_ENV=test
    - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - "6"
  - "8"
before_install:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - "curl -o- -L https://yarnpkg.com/install.sh | bash"
  - "export PATH=\"$HOME/.yarn/bin:$PATH\"" # Reload path so we can use yarn
  - "yarn global add gulp"
install:
  - "yarn install"
script:
  - npm run ci:code-review # Yarn does not support npm run
  - BEMUSE_COV=true gulp test
after_success:
  - codecov
  - 'cat coverage/lcov.info | ./node_modules/.bin/coveralls'
  - 'cat coverage/lcov.info | ./node_modules/.bin/codeclimate'
notifications:
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/31893c5fbae5d66e0a6f
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: true      # default: false
